# ISSF - Information System on Small Scale Fisheries
# Author: Joshua Murphy
# Date: December 23rd, 2018 
# https://github.com/toobigtoignore/issf

# Docker Compose file to orchestrate the containers needed to run ISSF
# as well as a PostgreSQL/PostGIS database

version: '2'

services: 
  web: 
    image: tbti/web:latest 
    #build: "."
    #command: "/bin/bash -c 'yes'"
    command: "/bin/sh -c 'npm i && python manage.py collectstatic --noinput && gunicorn issf_prod.wsgi -b 0.0.0.0:80'"
    depends_on: 
      - db
    environment: 
      - DJANGO_SETTINGS_MODULE=issf_prod.settings
    volumes:
      - "./:/issf:Z"
      - "./static:/static:Z"
    expose:
      - "80"
    stdin_open: true
    tty: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
  db: 
    image: mdillon/postgis:9.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./scripts:/scripts:Z"
      - "./data/postgres:/data/postgres/:Z"  
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
  pgadmin: 
    image: nphung/pgadmin:latest
    ports:
      - "5050:5050"
    volumes:
      - "./data/postgres:/data/postgres/:Z"
      - "./data/pgadmin:/data/pgadmin:Z"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - "./:/src:Z"
      - "./data/nginx:/etc/nginx/conf.d:Z"
      - "./static:/static:Z"
      - "~/issf_certs:/home/ubuntu/issf_certs:Z"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
